// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh98n9ElYwLP5KYGX97kJLP6s7fvpyfhs',
    appId: '1:965131363349:web:10a6943a0d435e4f661a1c',
    messagingSenderId: '965131363349',
    projectId: 'flutter-tutorial-8f739',
    authDomain: 'flutter-tutorial-8f739.firebaseapp.com',
    storageBucket: 'flutter-tutorial-8f739.appspot.com',
    measurementId: 'G-CC10E09NE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAurNkbU-q_NHXumfxlYLre-jyC35VOwlM',
    appId: '1:965131363349:android:ad8a70004f0f294b661a1c',
    messagingSenderId: '965131363349',
    projectId: 'flutter-tutorial-8f739',
    storageBucket: 'flutter-tutorial-8f739.appspot.com',
  );
}
